### ISSUE TITLE
Cant see the pannel in 2.93

### ISSUE THREAD

**Issue by cilbo** [snuq/Script-Shortcut#3]
addon sounds awsome!
sadly i cant get it to work.
alt+space brings up script shortcut popup, but other than that i dont see any place where i could start.

**Comment by snuq** [comment]
The panels are visible on my install of 2.93.  Which view type are you looking for the panel in? (ie, 3d view, sequencer, node editor), it can show up in different panel groups depending on the view type.  

Make sure you downloaded the master branch of script shortcut, the 2.79 or 2.80 branches will likely not work properly anymore.

Do you see any error messages in the system console when blender starts up? ('Window' menu > 'Toggle System Console').
