### ISSUE TITLE
Add Icons to buttons

### ISSUE THREAD

**Issue by mino159** [snuq/Script-Shortcut#4]
**Problem:**
If list of buttons gets too long, it becomes unintuitive. It would be great if I have option to select an icon that goes with my text on button or even only button with icon in it. 

**Solution I'd like:**
When creating button add option to select appropriate icon (from blender userface) to use with text or instead of text in the button

**Additional context**
you used it there too
![image](https://user-images.githubusercontent.com/18248865/184091681-1523a963-d1a0-492c-84de-fdd52d6bd643.png)
and blender is using them everywhere
![image](https://user-images.githubusercontent.com/18248865/184091712-00fcfc25-05db-4656-b55f-bf43abd9a0c0.png)

**Comment by snuq** [comment]
Good suggestion, I added it.  The icon selection is a bit weird unfortunately, but I'm not really sure how to improve it with the limited way blender allows for dialogs, and the huge amount of icons that blender has.
This will break any layouts saved to an external file, but any internally saved layouts or presets in .blend files shouldn't have any problems.
