### ISSUE TITLE
Having new scripts for old blend files

### ISSUE THREAD

**Issue by mesimsek** [snuq/Script-Shortcut#6]
Hello! Thanks a lot for this great addon, this is literally what I've been looking for. I am not sure if there is already a solution for what I need, but here is my issue. If I add a new script shortcut, it is not visible when I open old blend files. Is there a way to keep script shortcuts for all files regardless of when I added them?

**Comment by snuq** [comment]
The panel presets are saved in the blend files themselves. This was intended behavior as I feel the advantages of this outweigh the disadvantages.  The best I can suggest for your case is to make use of the panel layout saving/loading feature.
